#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00
#PBS -l vmem=16gb

#SBATCH --job-name=bl_resample_raw
#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --time=01:00:00

set -x
set -e

mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report

singularity exec docker://brainlife/mne:1.0.2 python3 main.py
